// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO businesses (name, slug, tax_percent, service_charge_percent)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, tax_percent, service_charge_percent, created_at
`

type CreateBusinessParams struct {
	Name                 string `json:"name"`
	Slug                 string `json:"slug"`
	TaxPercent           string `json:"tax_percent"`
	ServiceChargePercent string `json:"service_charge_percent"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRowContext(ctx, createBusiness,
		arg.Name,
		arg.Slug,
		arg.TaxPercent,
		arg.ServiceChargePercent,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.TaxPercent,
		&i.ServiceChargePercent,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, expires_at, revoked, created_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.UserID, arg.Token, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (business_id, branch_id, name, email, password_hash, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, branch_id, name, email, password_hash, role, is_active, created_at
`

type CreateUserParams struct {
	BusinessID   uuid.UUID     `json:"business_id"`
	BranchID     uuid.NullUUID `json:"branch_id"`
	Name         string        `json:"name"`
	Email        string        `json:"email"`
	PasswordHash string        `json:"password_hash"`
	Role         UserRole      `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.BusinessID,
		arg.BranchID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BranchID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT
    s.id,
    s.user_id,
    s.token,
    s.expires_at,
    s.revoked,
    s.created_at
FROM sessions s
WHERE s.token    = $1
  AND s.revoked  = false
  AND s.expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, business_id, branch_id, name, email, password_hash, role, is_active, created_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BranchID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, business_id, branch_id, name, email, password_hash, role, is_active, created_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BranchID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked = true
WHERE token = $1
`

func (q *Queries) RevokeSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeSession, token)
	return err
}
