// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branch.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (business_id, name, address)
VALUES ($1, $2, $3)
RETURNING id, business_id, name, address, is_active, created_at
`

type CreateBranchParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Name       string    `json:"name"`
	Address    string    `json:"address"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRowContext(ctx, createBranch, arg.BusinessID, arg.Name, arg.Address)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getBranchByID = `-- name: GetBranchByID :one
SELECT id, business_id, name, address, is_active, created_at
FROM branches
WHERE id          = $1
  AND business_id = $2
LIMIT 1
`

type GetBranchByIDParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetBranchByID(ctx context.Context, arg GetBranchByIDParams) (Branch, error) {
	row := q.db.QueryRowContext(ctx, getBranchByID, arg.ID, arg.BusinessID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listBranches = `-- name: ListBranches :many
SELECT id, business_id, name, address, is_active, created_at
FROM branches
WHERE business_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListBranches(ctx context.Context, businessID uuid.UUID) ([]Branch, error) {
	rows, err := q.db.QueryContext(ctx, listBranches, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE branches
SET
    name      = COALESCE($2, name),
    address   = COALESCE($3, address),
    is_active = COALESCE($4, is_active)
WHERE id          = $1
  AND business_id = $5
RETURNING id, business_id, name, address, is_active, created_at
`

type UpdateBranchParams struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Address    string    `json:"address"`
	IsActive   bool      `json:"is_active"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error) {
	row := q.db.QueryRowContext(ctx, updateBranch,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.IsActive,
		arg.BusinessID,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
