// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getBusiness = `-- name: GetBusiness :one
SELECT id, name, slug, tax_percent, service_charge_percent, created_at
FROM businesses
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBusiness(ctx context.Context, id uuid.UUID) (Business, error) {
	row := q.db.QueryRowContext(ctx, getBusiness, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.TaxPercent,
		&i.ServiceChargePercent,
		&i.CreatedAt,
	)
	return i, err
}

const updateBusiness = `-- name: UpdateBusiness :one
UPDATE businesses
SET
    name                   = COALESCE($2, name),
    tax_percent            = COALESCE($3, tax_percent),
    service_charge_percent = COALESCE($4, service_charge_percent)
WHERE id = $1
RETURNING id, name, slug, tax_percent, service_charge_percent, created_at
`

type UpdateBusinessParams struct {
	ID                   uuid.UUID `json:"id"`
	Name                 string    `json:"name"`
	TaxPercent           string    `json:"tax_percent"`
	ServiceChargePercent string    `json:"service_charge_percent"`
}

func (q *Queries) UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (Business, error) {
	row := q.db.QueryRowContext(ctx, updateBusiness,
		arg.ID,
		arg.Name,
		arg.TaxPercent,
		arg.ServiceChargePercent,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.TaxPercent,
		&i.ServiceChargePercent,
		&i.CreatedAt,
	)
	return i, err
}
