// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getCashierDashboard = `-- name: GetCashierDashboard :one
SELECT
    COUNT(*) FILTER (WHERE o.status = 'open')                                                     AS open_orders_count,
    COUNT(*) FILTER (WHERE o.status = 'paid' AND o.created_at >= CURRENT_DATE)                   AS orders_handled_today,
    COALESCE(
        SUM(p.amount_paid) FILTER (WHERE p.paid_at >= CURRENT_DATE),
        0
    )                                                                                             AS total_collected_today
FROM orders o
LEFT JOIN payments p ON p.order_id = o.id
WHERE o.business_id = $1
  AND o.cashier_id  = $2
`

type GetCashierDashboardParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	CashierID  uuid.UUID `json:"cashier_id"`
}

type GetCashierDashboardRow struct {
	OpenOrdersCount     int64       `json:"open_orders_count"`
	OrdersHandledToday  int64       `json:"orders_handled_today"`
	TotalCollectedToday interface{} `json:"total_collected_today"`
}

func (q *Queries) GetCashierDashboard(ctx context.Context, arg GetCashierDashboardParams) (GetCashierDashboardRow, error) {
	row := q.db.QueryRowContext(ctx, getCashierDashboard, arg.BusinessID, arg.CashierID)
	var i GetCashierDashboardRow
	err := row.Scan(&i.OpenOrdersCount, &i.OrdersHandledToday, &i.TotalCollectedToday)
	return i, err
}

const getOwnerDashboard = `-- name: GetOwnerDashboard :one
SELECT
    COUNT(*)    FILTER (WHERE o.status = 'paid' AND o.created_at >= CURRENT_DATE)                AS total_orders_today,
    COALESCE(
        SUM(t.total) FILTER (WHERE t.paid_at >= CURRENT_DATE),
        0
    )                                                                                             AS total_revenue_today
FROM orders o
LEFT JOIN transactions t ON t.order_id = o.id
WHERE o.business_id = $1
`

type GetOwnerDashboardRow struct {
	TotalOrdersToday  int64       `json:"total_orders_today"`
	TotalRevenueToday interface{} `json:"total_revenue_today"`
}

func (q *Queries) GetOwnerDashboard(ctx context.Context, businessID uuid.UUID) (GetOwnerDashboardRow, error) {
	row := q.db.QueryRowContext(ctx, getOwnerDashboard, businessID)
	var i GetOwnerDashboardRow
	err := row.Scan(&i.TotalOrdersToday, &i.TotalRevenueToday)
	return i, err
}

const getRevenuePerBranch = `-- name: GetRevenuePerBranch :many
SELECT
    b.id                              AS branch_id,
    b.name                            AS branch_name,
    COALESCE(SUM(t.total), 0)         AS revenue
FROM branches b
LEFT JOIN transactions t
    ON  t.branch_id   = b.id
    AND t.paid_at     >= CURRENT_DATE
WHERE b.business_id = $1
GROUP BY b.id, b.name
ORDER BY b.name ASC
`

type GetRevenuePerBranchRow struct {
	BranchID   uuid.UUID   `json:"branch_id"`
	BranchName string      `json:"branch_name"`
	Revenue    interface{} `json:"revenue"`
}

func (q *Queries) GetRevenuePerBranch(ctx context.Context, businessID uuid.UUID) ([]GetRevenuePerBranchRow, error) {
	rows, err := q.db.QueryContext(ctx, getRevenuePerBranch, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRevenuePerBranchRow{}
	for rows.Next() {
		var i GetRevenuePerBranchRow
		if err := rows.Scan(&i.BranchID, &i.BranchName, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopMenuItems = `-- name: GetTopMenuItems :many
SELECT
    oi.menu_item_id,
    mi.name                  AS menu_item_name,
    SUM(oi.quantity)::INT    AS total_sold,
    SUM(oi.subtotal)         AS total_revenue
FROM order_items   oi
JOIN menu_items    mi ON mi.id = oi.menu_item_id
JOIN orders        o  ON o.id  = oi.order_id
WHERE o.business_id = $1
  AND o.status      = 'paid'
  AND o.created_at  >= CURRENT_DATE
GROUP BY oi.menu_item_id, mi.name
ORDER BY total_sold DESC
LIMIT 5
`

type GetTopMenuItemsRow struct {
	MenuItemID   uuid.UUID `json:"menu_item_id"`
	MenuItemName string    `json:"menu_item_name"`
	TotalSold    int32     `json:"total_sold"`
	TotalRevenue int64     `json:"total_revenue"`
}

func (q *Queries) GetTopMenuItems(ctx context.Context, businessID uuid.UUID) ([]GetTopMenuItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopMenuItems, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopMenuItemsRow{}
	for rows.Next() {
		var i GetTopMenuItemsRow
		if err := rows.Scan(
			&i.MenuItemID,
			&i.MenuItemName,
			&i.TotalSold,
			&i.TotalRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
