// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menu_item_modifiers.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteMenuItemModifiers = `-- name: DeleteMenuItemModifiers :exec
DELETE FROM menu_item_modifiers
WHERE menu_item_id = $1
`

func (q *Queries) DeleteMenuItemModifiers(ctx context.Context, menuItemID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMenuItemModifiers, menuItemID)
	return err
}

const getModifierGroupIDsByMenuItem = `-- name: GetModifierGroupIDsByMenuItem :many
SELECT modifier_group_id FROM menu_item_modifiers
WHERE menu_item_id = $1
`

func (q *Queries) GetModifierGroupIDsByMenuItem(ctx context.Context, menuItemID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getModifierGroupIDsByMenuItem, menuItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var modifier_group_id uuid.UUID
		if err := rows.Scan(&modifier_group_id); err != nil {
			return nil, err
		}
		items = append(items, modifier_group_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModifierGroupsWithOptionsByMenuItem = `-- name: GetModifierGroupsWithOptionsByMenuItem :many
SELECT
    mg.id           AS group_id,
    mg.name         AS group_name,
    mg.is_required,
    mg.max_select,
    mo.id           AS option_id,
    mo.name         AS option_name,
    mo.extra_price
FROM menu_item_modifiers mim
JOIN modifier_groups mg ON mg.id = mim.modifier_group_id
JOIN modifier_options mo ON mo.group_id = mg.id
WHERE mim.menu_item_id = $1
ORDER BY mg.name, mo.name
`

type GetModifierGroupsWithOptionsByMenuItemRow struct {
	GroupID    uuid.UUID `json:"group_id"`
	GroupName  string    `json:"group_name"`
	IsRequired bool      `json:"is_required"`
	MaxSelect  int32     `json:"max_select"`
	OptionID   uuid.UUID `json:"option_id"`
	OptionName string    `json:"option_name"`
	ExtraPrice string    `json:"extra_price"`
}

func (q *Queries) GetModifierGroupsWithOptionsByMenuItem(ctx context.Context, menuItemID uuid.UUID) ([]GetModifierGroupsWithOptionsByMenuItemRow, error) {
	rows, err := q.db.QueryContext(ctx, getModifierGroupsWithOptionsByMenuItem, menuItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetModifierGroupsWithOptionsByMenuItemRow{}
	for rows.Next() {
		var i GetModifierGroupsWithOptionsByMenuItemRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.IsRequired,
			&i.MaxSelect,
			&i.OptionID,
			&i.OptionName,
			&i.ExtraPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkModifierGroupToMenuItem = `-- name: LinkModifierGroupToMenuItem :exec
INSERT INTO menu_item_modifiers (menu_item_id, modifier_group_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkModifierGroupToMenuItemParams struct {
	MenuItemID      uuid.UUID `json:"menu_item_id"`
	ModifierGroupID uuid.UUID `json:"modifier_group_id"`
}

func (q *Queries) LinkModifierGroupToMenuItem(ctx context.Context, arg LinkModifierGroupToMenuItemParams) error {
	_, err := q.db.ExecContext(ctx, linkModifierGroupToMenuItem, arg.MenuItemID, arg.ModifierGroupID)
	return err
}
