// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menu.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_items (business_id, name, description, price, category, is_available)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, name, description, price, category, is_available, created_at
`

type CreateMenuItemParams struct {
	BusinessID  uuid.UUID `json:"business_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Price       string    `json:"price"`
	Category    string    `json:"category"`
	IsAvailable bool      `json:"is_available"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRowContext(ctx, createMenuItem,
		arg.BusinessID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Category,
		arg.IsAvailable,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.IsAvailable,
		&i.CreatedAt,
	)
	return i, err
}

const getMenuItemByID = `-- name: GetMenuItemByID :one
SELECT id, business_id, name, description, price, category, is_available, created_at
FROM menu_items
WHERE id          = $1
  AND business_id = $2
LIMIT 1
`

type GetMenuItemByIDParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetMenuItemByID(ctx context.Context, arg GetMenuItemByIDParams) (MenuItem, error) {
	row := q.db.QueryRowContext(ctx, getMenuItemByID, arg.ID, arg.BusinessID)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.IsAvailable,
		&i.CreatedAt,
	)
	return i, err
}

const listMenuItems = `-- name: ListMenuItems :many
SELECT id, business_id, name, description, price, category, is_available, created_at
FROM menu_items
WHERE business_id = $1
ORDER BY category ASC, name ASC
`

func (q *Queries) ListMenuItems(ctx context.Context, businessID uuid.UUID) ([]MenuItem, error) {
	rows, err := q.db.QueryContext(ctx, listMenuItems, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Category,
			&i.IsAvailable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenuItem = `-- name: UpdateMenuItem :one
UPDATE menu_items
SET
    name         = COALESCE($2, name),
    description  = COALESCE($3, description),
    price        = COALESCE($4, price),
    category     = COALESCE($5, category),
    is_available = COALESCE($6, is_available)
WHERE id          = $1
  AND business_id = $7
RETURNING id, business_id, name, description, price, category, is_available, created_at
`

type UpdateMenuItemParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Price       string    `json:"price"`
	Category    string    `json:"category"`
	IsAvailable bool      `json:"is_available"`
	BusinessID  uuid.UUID `json:"business_id"`
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRowContext(ctx, updateMenuItem,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Category,
		arg.IsAvailable,
		arg.BusinessID,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.IsAvailable,
		&i.CreatedAt,
	)
	return i, err
}
