// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type OrderStatus string

const (
	OrderStatusOpen      OrderStatus = "open"
	OrderStatusPaid      OrderStatus = "paid"
	OrderStatusCancelled OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type OrderType string

const (
	OrderTypeDineIn   OrderType = "dine_in"
	OrderTypeTakeaway OrderType = "takeaway"
)

func (e *OrderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderType(s)
	case string:
		*e = OrderType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderType: %T", src)
	}
	return nil
}

type NullOrderType struct {
	OrderType OrderType `json:"order_type"`
	Valid     bool      `json:"valid"` // Valid is true if OrderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderType) Scan(value interface{}) error {
	if value == nil {
		ns.OrderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderType), nil
}

type PaymentMethod string

const (
	PaymentMethodCash     PaymentMethod = "cash"
	PaymentMethodQris     PaymentMethod = "qris"
	PaymentMethodTransfer PaymentMethod = "transfer"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type TableStatus string

const (
	TableStatusAvailable TableStatus = "available"
	TableStatusOccupied  TableStatus = "occupied"
)

func (e *TableStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TableStatus(s)
	case string:
		*e = TableStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TableStatus: %T", src)
	}
	return nil
}

type NullTableStatus struct {
	TableStatus TableStatus `json:"table_status"`
	Valid       bool        `json:"valid"` // Valid is true if TableStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTableStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TableStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TableStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTableStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TableStatus), nil
}

type UserRole string

const (
	UserRoleOwner   UserRole = "owner"
	UserRoleCashier UserRole = "cashier"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Branch struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
	Name       string    `json:"name"`
	Address    string    `json:"address"`
	IsActive   bool      `json:"is_active"`
	CreatedAt  time.Time `json:"created_at"`
}

type Business struct {
	ID                   uuid.UUID `json:"id"`
	Name                 string    `json:"name"`
	Slug                 string    `json:"slug"`
	TaxPercent           string    `json:"tax_percent"`
	ServiceChargePercent string    `json:"service_charge_percent"`
	CreatedAt            time.Time `json:"created_at"`
}

type MenuItem struct {
	ID          uuid.UUID `json:"id"`
	BusinessID  uuid.UUID `json:"business_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Price       string    `json:"price"`
	Category    string    `json:"category"`
	IsAvailable bool      `json:"is_available"`
	CreatedAt   time.Time `json:"created_at"`
}

type ModifierGroup struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
	Name       string    `json:"name"`
	IsRequired bool      `json:"is_required"`
	MaxSelect  int32     `json:"max_select"`
}

type ModifierOption struct {
	ID         uuid.UUID `json:"id"`
	GroupID    uuid.UUID `json:"group_id"`
	Name       string    `json:"name"`
	ExtraPrice string    `json:"extra_price"`
}

type Order struct {
	ID                  uuid.UUID     `json:"id"`
	BusinessID          uuid.UUID     `json:"business_id"`
	BranchID            uuid.UUID     `json:"branch_id"`
	CashierID           uuid.UUID     `json:"cashier_id"`
	TableID             uuid.NullUUID `json:"table_id"`
	Type                OrderType     `json:"type"`
	CustomerName        string        `json:"customer_name"`
	Status              OrderStatus   `json:"status"`
	Subtotal            string        `json:"subtotal"`
	TaxAmount           string        `json:"tax_amount"`
	ServiceChargeAmount string        `json:"service_charge_amount"`
	Total               string        `json:"total"`
	CreatedAt           time.Time     `json:"created_at"`
}

type OrderItem struct {
	ID         uuid.UUID `json:"id"`
	OrderID    uuid.UUID `json:"order_id"`
	MenuItemID uuid.UUID `json:"menu_item_id"`
	Quantity   int32     `json:"quantity"`
	UnitPrice  string    `json:"unit_price"`
	Notes      string    `json:"notes"`
	Subtotal   string    `json:"subtotal"`
}

type OrderItemModifier struct {
	ID               uuid.UUID `json:"id"`
	OrderItemID      uuid.UUID `json:"order_item_id"`
	ModifierOptionID uuid.UUID `json:"modifier_option_id"`
	ExtraPrice       string    `json:"extra_price"`
}

type Payment struct {
	ID           uuid.UUID     `json:"id"`
	OrderID      uuid.UUID     `json:"order_id"`
	Method       PaymentMethod `json:"method"`
	AmountPaid   string        `json:"amount_paid"`
	ChangeAmount string        `json:"change_amount"`
	PaidAt       time.Time     `json:"paid_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	Revoked   bool      `json:"revoked"`
	CreatedAt time.Time `json:"created_at"`
}

type Table struct {
	ID        uuid.UUID   `json:"id"`
	BranchID  uuid.UUID   `json:"branch_id"`
	Name      string      `json:"name"`
	QrCode    string      `json:"qr_code"`
	Status    TableStatus `json:"status"`
	CreatedAt time.Time   `json:"created_at"`
}

type Transaction struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
	OrderID    uuid.UUID `json:"order_id"`
	BranchID   uuid.UUID `json:"branch_id"`
	Total      string    `json:"total"`
	PaidAt     time.Time `json:"paid_at"`
}

type User struct {
	ID           uuid.UUID     `json:"id"`
	BusinessID   uuid.UUID     `json:"business_id"`
	BranchID     uuid.NullUUID `json:"branch_id"`
	Name         string        `json:"name"`
	Email        string        `json:"email"`
	PasswordHash string        `json:"password_hash"`
	Role         UserRole      `json:"role"`
	IsActive     bool          `json:"is_active"`
	CreatedAt    time.Time     `json:"created_at"`
}
