// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modifier.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createModifierGroup = `-- name: CreateModifierGroup :one
INSERT INTO modifier_groups (business_id, name, is_required, max_select)
VALUES ($1, $2, $3, $4)
RETURNING id, business_id, name, is_required, max_select
`

type CreateModifierGroupParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Name       string    `json:"name"`
	IsRequired bool      `json:"is_required"`
	MaxSelect  int32     `json:"max_select"`
}

func (q *Queries) CreateModifierGroup(ctx context.Context, arg CreateModifierGroupParams) (ModifierGroup, error) {
	row := q.db.QueryRowContext(ctx, createModifierGroup,
		arg.BusinessID,
		arg.Name,
		arg.IsRequired,
		arg.MaxSelect,
	)
	var i ModifierGroup
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.IsRequired,
		&i.MaxSelect,
	)
	return i, err
}

const createModifierOption = `-- name: CreateModifierOption :one
INSERT INTO modifier_options (group_id, name, extra_price)
VALUES ($1, $2, $3)
RETURNING id, group_id, name, extra_price
`

type CreateModifierOptionParams struct {
	GroupID    uuid.UUID `json:"group_id"`
	Name       string    `json:"name"`
	ExtraPrice string    `json:"extra_price"`
}

func (q *Queries) CreateModifierOption(ctx context.Context, arg CreateModifierOptionParams) (ModifierOption, error) {
	row := q.db.QueryRowContext(ctx, createModifierOption, arg.GroupID, arg.Name, arg.ExtraPrice)
	var i ModifierOption
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.ExtraPrice,
	)
	return i, err
}

const getModifierGroupByID = `-- name: GetModifierGroupByID :one
SELECT id, business_id, name, is_required, max_select
FROM modifier_groups
WHERE id          = $1
  AND business_id = $2
LIMIT 1
`

type GetModifierGroupByIDParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetModifierGroupByID(ctx context.Context, arg GetModifierGroupByIDParams) (ModifierGroup, error) {
	row := q.db.QueryRowContext(ctx, getModifierGroupByID, arg.ID, arg.BusinessID)
	var i ModifierGroup
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.IsRequired,
		&i.MaxSelect,
	)
	return i, err
}

const getModifierOptionByID = `-- name: GetModifierOptionByID :one
SELECT id, group_id, name, extra_price
FROM modifier_options
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetModifierOptionByID(ctx context.Context, id uuid.UUID) (ModifierOption, error) {
	row := q.db.QueryRowContext(ctx, getModifierOptionByID, id)
	var i ModifierOption
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.ExtraPrice,
	)
	return i, err
}

const listModifierGroups = `-- name: ListModifierGroups :many
SELECT id, business_id, name, is_required, max_select
FROM modifier_groups
WHERE business_id = $1
ORDER BY name ASC
`

func (q *Queries) ListModifierGroups(ctx context.Context, businessID uuid.UUID) ([]ModifierGroup, error) {
	rows, err := q.db.QueryContext(ctx, listModifierGroups, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModifierGroup{}
	for rows.Next() {
		var i ModifierGroup
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.IsRequired,
			&i.MaxSelect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifierOptions = `-- name: ListModifierOptions :many
SELECT id, group_id, name, extra_price
FROM modifier_options
WHERE group_id = $1
ORDER BY name ASC
`

func (q *Queries) ListModifierOptions(ctx context.Context, groupID uuid.UUID) ([]ModifierOption, error) {
	rows, err := q.db.QueryContext(ctx, listModifierOptions, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModifierOption{}
	for rows.Next() {
		var i ModifierOption
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.ExtraPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModifierGroup = `-- name: UpdateModifierGroup :one
UPDATE modifier_groups
SET
    name        = COALESCE($2, name),
    is_required = COALESCE($3, is_required),
    max_select  = COALESCE($4, max_select)
WHERE id          = $1
  AND business_id = $5
RETURNING id, business_id, name, is_required, max_select
`

type UpdateModifierGroupParams struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	IsRequired bool      `json:"is_required"`
	MaxSelect  int32     `json:"max_select"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) UpdateModifierGroup(ctx context.Context, arg UpdateModifierGroupParams) (ModifierGroup, error) {
	row := q.db.QueryRowContext(ctx, updateModifierGroup,
		arg.ID,
		arg.Name,
		arg.IsRequired,
		arg.MaxSelect,
		arg.BusinessID,
	)
	var i ModifierGroup
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.IsRequired,
		&i.MaxSelect,
	)
	return i, err
}
