// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const addOrderItem = `-- name: AddOrderItem :one
INSERT INTO order_items (order_id, menu_item_id, quantity, unit_price, notes, subtotal)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, menu_item_id, quantity, unit_price, notes, subtotal
`

type AddOrderItemParams struct {
	OrderID    uuid.UUID `json:"order_id"`
	MenuItemID uuid.UUID `json:"menu_item_id"`
	Quantity   int32     `json:"quantity"`
	UnitPrice  string    `json:"unit_price"`
	Notes      string    `json:"notes"`
	Subtotal   string    `json:"subtotal"`
}

func (q *Queries) AddOrderItem(ctx context.Context, arg AddOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, addOrderItem,
		arg.OrderID,
		arg.MenuItemID,
		arg.Quantity,
		arg.UnitPrice,
		arg.Notes,
		arg.Subtotal,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuItemID,
		&i.Quantity,
		&i.UnitPrice,
		&i.Notes,
		&i.Subtotal,
	)
	return i, err
}

const addOrderItemModifier = `-- name: AddOrderItemModifier :one
INSERT INTO order_item_modifiers (order_item_id, modifier_option_id, extra_price)
VALUES ($1, $2, $3)
RETURNING id, order_item_id, modifier_option_id, extra_price
`

type AddOrderItemModifierParams struct {
	OrderItemID      uuid.UUID `json:"order_item_id"`
	ModifierOptionID uuid.UUID `json:"modifier_option_id"`
	ExtraPrice       string    `json:"extra_price"`
}

func (q *Queries) AddOrderItemModifier(ctx context.Context, arg AddOrderItemModifierParams) (OrderItemModifier, error) {
	row := q.db.QueryRowContext(ctx, addOrderItemModifier, arg.OrderItemID, arg.ModifierOptionID, arg.ExtraPrice)
	var i OrderItemModifier
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.ModifierOptionID,
		&i.ExtraPrice,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (business_id, branch_id, cashier_id, table_id, type, customer_name)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, branch_id, cashier_id, table_id, type, customer_name, status, subtotal, tax_amount, service_charge_amount, total, created_at
`

type CreateOrderParams struct {
	BusinessID   uuid.UUID     `json:"business_id"`
	BranchID     uuid.UUID     `json:"branch_id"`
	CashierID    uuid.UUID     `json:"cashier_id"`
	TableID      uuid.NullUUID `json:"table_id"`
	Type         OrderType     `json:"type"`
	CustomerName string        `json:"customer_name"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.BusinessID,
		arg.BranchID,
		arg.CashierID,
		arg.TableID,
		arg.Type,
		arg.CustomerName,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BranchID,
		&i.CashierID,
		&i.TableID,
		&i.Type,
		&i.CustomerName,
		&i.Status,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ServiceChargeAmount,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrderItem = `-- name: DeleteOrderItem :exec
DELETE FROM order_items
WHERE id       = $1
  AND order_id = $2
`

type DeleteOrderItemParams struct {
	ID      uuid.UUID `json:"id"`
	OrderID uuid.UUID `json:"order_id"`
}

func (q *Queries) DeleteOrderItem(ctx context.Context, arg DeleteOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteOrderItem, arg.ID, arg.OrderID)
	return err
}

const deleteOrderItemModifiers = `-- name: DeleteOrderItemModifiers :exec
DELETE FROM order_item_modifiers
WHERE order_item_id = $1
`

func (q *Queries) DeleteOrderItemModifiers(ctx context.Context, orderItemID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrderItemModifiers, orderItemID)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, business_id, branch_id, cashier_id, table_id, type, customer_name, status, subtotal, tax_amount, service_charge_amount, total, created_at
FROM orders
WHERE id          = $1
  AND business_id = $2
LIMIT 1
`

type GetOrderByIDParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, arg.ID, arg.BusinessID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BranchID,
		&i.CashierID,
		&i.TableID,
		&i.Type,
		&i.CustomerName,
		&i.Status,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ServiceChargeAmount,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByIDForUpdate = `-- name: GetOrderByIDForUpdate :one
SELECT id, business_id, branch_id, cashier_id, table_id, type, customer_name, status, subtotal, tax_amount, service_charge_amount, total, created_at
FROM orders
WHERE id          = $1
  AND business_id = $2
LIMIT 1
FOR UPDATE
`

type GetOrderByIDForUpdateParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetOrderByIDForUpdate(ctx context.Context, arg GetOrderByIDForUpdateParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByIDForUpdate, arg.ID, arg.BusinessID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BranchID,
		&i.CashierID,
		&i.TableID,
		&i.Type,
		&i.CustomerName,
		&i.Status,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ServiceChargeAmount,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderItemByID = `-- name: GetOrderItemByID :one
SELECT id, order_id, menu_item_id, quantity, unit_price, notes, subtotal
FROM order_items
WHERE id       = $1
  AND order_id = $2
LIMIT 1
`

type GetOrderItemByIDParams struct {
	ID      uuid.UUID `json:"id"`
	OrderID uuid.UUID `json:"order_id"`
}

func (q *Queries) GetOrderItemByID(ctx context.Context, arg GetOrderItemByIDParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, getOrderItemByID, arg.ID, arg.OrderID)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuItemID,
		&i.Quantity,
		&i.UnitPrice,
		&i.Notes,
		&i.Subtotal,
	)
	return i, err
}

const listOrderItemModifiers = `-- name: ListOrderItemModifiers :many
SELECT id, order_item_id, modifier_option_id, extra_price
FROM order_item_modifiers
WHERE order_item_id = $1
`

func (q *Queries) ListOrderItemModifiers(ctx context.Context, orderItemID uuid.UUID) ([]OrderItemModifier, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemModifiers, orderItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItemModifier{}
	for rows.Next() {
		var i OrderItemModifier
		if err := rows.Scan(
			&i.ID,
			&i.OrderItemID,
			&i.ModifierOptionID,
			&i.ExtraPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, menu_item_id, quantity, unit_price, notes, subtotal
FROM order_items
WHERE order_id = $1
ORDER BY id
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.MenuItemID,
			&i.Quantity,
			&i.UnitPrice,
			&i.Notes,
			&i.Subtotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByStatus = `-- name: ListOrdersByStatus :many
SELECT id, business_id, branch_id, cashier_id, table_id, type, customer_name, status, subtotal, tax_amount, service_charge_amount, total, created_at
FROM orders
WHERE business_id = $1
  AND status      = $2
ORDER BY created_at DESC
`

type ListOrdersByStatusParams struct {
	BusinessID uuid.UUID   `json:"business_id"`
	Status     OrderStatus `json:"status"`
}

func (q *Queries) ListOrdersByStatus(ctx context.Context, arg ListOrdersByStatusParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByStatus, arg.BusinessID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.BranchID,
			&i.CashierID,
			&i.TableID,
			&i.Type,
			&i.CustomerName,
			&i.Status,
			&i.Subtotal,
			&i.TaxAmount,
			&i.ServiceChargeAmount,
			&i.Total,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByStatusAndBranch = `-- name: ListOrdersByStatusAndBranch :many
SELECT id, business_id, branch_id, cashier_id, table_id, type, customer_name, status, subtotal, tax_amount, service_charge_amount, total, created_at
FROM orders
WHERE business_id = $1
  AND branch_id   = $2
  AND status      = $3
ORDER BY created_at DESC
`

type ListOrdersByStatusAndBranchParams struct {
	BusinessID uuid.UUID   `json:"business_id"`
	BranchID   uuid.UUID   `json:"branch_id"`
	Status     OrderStatus `json:"status"`
}

func (q *Queries) ListOrdersByStatusAndBranch(ctx context.Context, arg ListOrdersByStatusAndBranchParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByStatusAndBranch, arg.BusinessID, arg.BranchID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.BranchID,
			&i.CashierID,
			&i.TableID,
			&i.Type,
			&i.CustomerName,
			&i.Status,
			&i.Subtotal,
			&i.TaxAmount,
			&i.ServiceChargeAmount,
			&i.Total,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderItem = `-- name: UpdateOrderItem :one
UPDATE order_items
SET
    quantity = COALESCE($2, quantity),
    notes    = COALESCE($3, notes),
    subtotal = COALESCE($4, subtotal)
WHERE id       = $1
  AND order_id = $5
RETURNING id, order_id, menu_item_id, quantity, unit_price, notes, subtotal
`

type UpdateOrderItemParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
	Notes    string    `json:"notes"`
	Subtotal string    `json:"subtotal"`
	OrderID  uuid.UUID `json:"order_id"`
}

func (q *Queries) UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, updateOrderItem,
		arg.ID,
		arg.Quantity,
		arg.Notes,
		arg.Subtotal,
		arg.OrderID,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuItemID,
		&i.Quantity,
		&i.UnitPrice,
		&i.Notes,
		&i.Subtotal,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2
WHERE id          = $1
  AND business_id = $3
RETURNING id, business_id, branch_id, cashier_id, table_id, type, customer_name, status, subtotal, tax_amount, service_charge_amount, total, created_at
`

type UpdateOrderStatusParams struct {
	ID         uuid.UUID   `json:"id"`
	Status     OrderStatus `json:"status"`
	BusinessID uuid.UUID   `json:"business_id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, arg.ID, arg.Status, arg.BusinessID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BranchID,
		&i.CashierID,
		&i.TableID,
		&i.Type,
		&i.CustomerName,
		&i.Status,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ServiceChargeAmount,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrderTotals = `-- name: UpdateOrderTotals :one
UPDATE orders
SET
    subtotal              = $2,
    tax_amount            = $3,
    service_charge_amount = $4,
    total                 = $5
WHERE id = $1
RETURNING id, business_id, branch_id, cashier_id, table_id, type, customer_name, status, subtotal, tax_amount, service_charge_amount, total, created_at
`

type UpdateOrderTotalsParams struct {
	ID                  uuid.UUID `json:"id"`
	Subtotal            string    `json:"subtotal"`
	TaxAmount           string    `json:"tax_amount"`
	ServiceChargeAmount string    `json:"service_charge_amount"`
	Total               string    `json:"total"`
}

func (q *Queries) UpdateOrderTotals(ctx context.Context, arg UpdateOrderTotalsParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderTotals,
		arg.ID,
		arg.Subtotal,
		arg.TaxAmount,
		arg.ServiceChargeAmount,
		arg.Total,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BranchID,
		&i.CashierID,
		&i.TableID,
		&i.Type,
		&i.CustomerName,
		&i.Status,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ServiceChargeAmount,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}
