// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id, method, amount_paid, change_amount)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, method, amount_paid, change_amount, paid_at
`

type CreatePaymentParams struct {
	OrderID      uuid.UUID     `json:"order_id"`
	Method       PaymentMethod `json:"method"`
	AmountPaid   string        `json:"amount_paid"`
	ChangeAmount string        `json:"change_amount"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.OrderID,
		arg.Method,
		arg.AmountPaid,
		arg.ChangeAmount,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Method,
		&i.AmountPaid,
		&i.ChangeAmount,
		&i.PaidAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (business_id, order_id, branch_id, total)
VALUES ($1, $2, $3, $4)
RETURNING id, business_id, order_id, branch_id, total, paid_at
`

type CreateTransactionParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	OrderID    uuid.UUID `json:"order_id"`
	BranchID   uuid.UUID `json:"branch_id"`
	Total      string    `json:"total"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.BusinessID,
		arg.OrderID,
		arg.BranchID,
		arg.Total,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OrderID,
		&i.BranchID,
		&i.Total,
		&i.PaidAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, method, amount_paid, change_amount, paid_at
FROM payments
WHERE order_id = $1
LIMIT 1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Method,
		&i.AmountPaid,
		&i.ChangeAmount,
		&i.PaidAt,
	)
	return i, err
}
