// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: qris.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deactivateBranchQRIS = `-- name: DeactivateBranchQRIS :exec
UPDATE branch_qris
SET is_active = false
WHERE branch_id = $1
`

func (q *Queries) DeactivateBranchQRIS(ctx context.Context, branchID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateBranchQRIS, branchID)
	return err
}

const getActiveBranchQRIS = `-- name: GetActiveBranchQRIS :one
SELECT id, branch_id, qris_string, image_path, uploaded_by, is_active, created_at FROM branch_qris
WHERE branch_id = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetActiveBranchQRIS(ctx context.Context, branchID uuid.UUID) (BranchQri, error) {
	row := q.db.QueryRowContext(ctx, getActiveBranchQRIS, branchID)
	var i BranchQri
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.QrisString,
		&i.ImagePath,
		&i.UploadedBy,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const insertBranchQRIS = `-- name: InsertBranchQRIS :one
INSERT INTO branch_qris (id, branch_id, qris_string, image_path, uploaded_by, is_active, created_at)
VALUES ($1, $2, $3, $4, $5, true, NOW())
RETURNING id, branch_id, qris_string, image_path, uploaded_by, is_active, created_at
`

type InsertBranchQRISParams struct {
	ID         uuid.UUID     `json:"id"`
	BranchID   uuid.UUID     `json:"branch_id"`
	QrisString string        `json:"qris_string"`
	ImagePath  string        `json:"image_path"`
	UploadedBy uuid.NullUUID `json:"uploaded_by"`
}

func (q *Queries) InsertBranchQRIS(ctx context.Context, arg InsertBranchQRISParams) (BranchQri, error) {
	row := q.db.QueryRowContext(ctx, insertBranchQRIS,
		arg.ID,
		arg.BranchID,
		arg.QrisString,
		arg.ImagePath,
		arg.UploadedBy,
	)
	var i BranchQri
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.QrisString,
		&i.ImagePath,
		&i.UploadedBy,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listBranchQRISHistory = `-- name: ListBranchQRISHistory :many
SELECT id, branch_id, qris_string, image_path, uploaded_by, is_active, created_at FROM branch_qris
WHERE branch_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBranchQRISHistory(ctx context.Context, branchID uuid.UUID) ([]BranchQri, error) {
	rows, err := q.db.QueryContext(ctx, listBranchQRISHistory, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchQri{}
	for rows.Next() {
		var i BranchQri
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.QrisString,
			&i.ImagePath,
			&i.UploadedBy,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
