// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddOrderItem(ctx context.Context, arg AddOrderItemParams) (OrderItem, error)
	AddOrderItemModifier(ctx context.Context, arg AddOrderItemModifierParams) (OrderItemModifier, error)
	CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error)
	CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error)
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error)
	CreateModifierGroup(ctx context.Context, arg CreateModifierGroupParams) (ModifierGroup, error)
	CreateModifierOption(ctx context.Context, arg CreateModifierOptionParams) (ModifierOption, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStaff(ctx context.Context, arg CreateStaffParams) (User, error)
	CreateTable(ctx context.Context, arg CreateTableParams) (Table, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteOrderItem(ctx context.Context, arg DeleteOrderItemParams) error
	DeleteOrderItemModifiers(ctx context.Context, orderItemID uuid.UUID) error
	GetBranchByID(ctx context.Context, arg GetBranchByIDParams) (Branch, error)
	GetBusiness(ctx context.Context, id uuid.UUID) (Business, error)
	GetCashierDashboard(ctx context.Context, arg GetCashierDashboardParams) (GetCashierDashboardRow, error)
	GetMenuItemByID(ctx context.Context, arg GetMenuItemByIDParams) (MenuItem, error)
	GetModifierGroupByID(ctx context.Context, arg GetModifierGroupByIDParams) (ModifierGroup, error)
	GetModifierOptionByID(ctx context.Context, id uuid.UUID) (ModifierOption, error)
	GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (Order, error)
	GetOrderByIDForUpdate(ctx context.Context, arg GetOrderByIDForUpdateParams) (Order, error)
	GetOrderItemByID(ctx context.Context, arg GetOrderItemByIDParams) (OrderItem, error)
	GetOwnerDashboard(ctx context.Context, businessID uuid.UUID) (GetOwnerDashboardRow, error)
	GetPaymentByOrderID(ctx context.Context, orderID uuid.UUID) (Payment, error)
	GetRevenuePerBranch(ctx context.Context, businessID uuid.UUID) ([]GetRevenuePerBranchRow, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetStaffByID(ctx context.Context, arg GetStaffByIDParams) (User, error)
	GetTableByID(ctx context.Context, arg GetTableByIDParams) (Table, error)
	GetTopMenuItems(ctx context.Context, businessID uuid.UUID) ([]GetTopMenuItemsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListBranches(ctx context.Context, businessID uuid.UUID) ([]Branch, error)
	ListMenuItems(ctx context.Context, businessID uuid.UUID) ([]MenuItem, error)
	ListModifierGroups(ctx context.Context, businessID uuid.UUID) ([]ModifierGroup, error)
	ListModifierOptions(ctx context.Context, groupID uuid.UUID) ([]ModifierOption, error)
	ListOrderItemModifiers(ctx context.Context, orderItemID uuid.UUID) ([]OrderItemModifier, error)
	ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	ListOrdersByStatus(ctx context.Context, arg ListOrdersByStatusParams) ([]Order, error)
	ListOrdersByStatusAndBranch(ctx context.Context, arg ListOrdersByStatusAndBranchParams) ([]Order, error)
	ListStaff(ctx context.Context, businessID uuid.UUID) ([]User, error)
	ListTables(ctx context.Context, arg ListTablesParams) ([]Table, error)
	ListTablesByBusiness(ctx context.Context, businessID uuid.UUID) ([]Table, error)
	RevokeSession(ctx context.Context, token string) error
	SetTableAvailable(ctx context.Context, id uuid.UUID) error
	UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error)
	UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (Business, error)
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error)
	UpdateModifierGroup(ctx context.Context, arg UpdateModifierGroupParams) (ModifierGroup, error)
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateOrderTotals(ctx context.Context, arg UpdateOrderTotalsParams) (Order, error)
	UpdateStaffStatus(ctx context.Context, arg UpdateStaffStatusParams) (User, error)
	UpdateTable(ctx context.Context, arg UpdateTableParams) (Table, error)
}

var _ Querier = (*Queries)(nil)
