// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: receipt.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getReceiptData = `-- name: GetReceiptData :one
SELECT
    o.id                        AS order_id,
    o.type                      AS order_type,
    o.customer_name,
    o.status                    AS order_status,
    o.subtotal,
    o.tax_amount,
    o.service_charge_amount,
    o.total,
    o.created_at                AS ordered_at,
    b.name                      AS business_name,
    b.image_url                 AS business_logo_url,
    b.tax_percent,
    b.service_charge_percent,
    br.name                     AS branch_name,
    br.address                  AS branch_address,
    u.name                      AS cashier_name,
    p.method                    AS payment_method,
    p.amount_paid,
    p.change_amount,
    p.paid_at
FROM orders o
JOIN businesses b  ON b.id = o.business_id
JOIN branches br   ON br.id = o.branch_id
JOIN users u       ON u.id = o.cashier_id
JOIN payments p    ON p.order_id = o.id
WHERE o.id = $1 AND o.business_id = $2
`

type GetReceiptDataParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

type GetReceiptDataRow struct {
	OrderID              uuid.UUID      `json:"order_id"`
	OrderType            OrderType      `json:"order_type"`
	CustomerName         string         `json:"customer_name"`
	OrderStatus          OrderStatus    `json:"order_status"`
	Subtotal             string         `json:"subtotal"`
	TaxAmount            string         `json:"tax_amount"`
	ServiceChargeAmount  string         `json:"service_charge_amount"`
	Total                string         `json:"total"`
	OrderedAt            time.Time      `json:"ordered_at"`
	BusinessName         string         `json:"business_name"`
	BusinessLogoUrl      sql.NullString `json:"business_logo_url"`
	TaxPercent           string         `json:"tax_percent"`
	ServiceChargePercent string         `json:"service_charge_percent"`
	BranchName           string         `json:"branch_name"`
	BranchAddress        string         `json:"branch_address"`
	CashierName          string         `json:"cashier_name"`
	PaymentMethod        PaymentMethod  `json:"payment_method"`
	AmountPaid           string         `json:"amount_paid"`
	ChangeAmount         string         `json:"change_amount"`
	PaidAt               time.Time      `json:"paid_at"`
}

func (q *Queries) GetReceiptData(ctx context.Context, arg GetReceiptDataParams) (GetReceiptDataRow, error) {
	row := q.db.QueryRowContext(ctx, getReceiptData, arg.ID, arg.BusinessID)
	var i GetReceiptDataRow
	err := row.Scan(
		&i.OrderID,
		&i.OrderType,
		&i.CustomerName,
		&i.OrderStatus,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ServiceChargeAmount,
		&i.Total,
		&i.OrderedAt,
		&i.BusinessName,
		&i.BusinessLogoUrl,
		&i.TaxPercent,
		&i.ServiceChargePercent,
		&i.BranchName,
		&i.BranchAddress,
		&i.CashierName,
		&i.PaymentMethod,
		&i.AmountPaid,
		&i.ChangeAmount,
		&i.PaidAt,
	)
	return i, err
}

const getReceiptItemModifiers = `-- name: GetReceiptItemModifiers :many
SELECT
    oim.order_item_id,
    mo.name         AS modifier_name,
    oim.extra_price
FROM order_item_modifiers oim
JOIN modifier_options mo ON mo.id = oim.modifier_option_id
WHERE oim.order_item_id = ANY($1::uuid[])
`

type GetReceiptItemModifiersRow struct {
	OrderItemID  uuid.UUID `json:"order_item_id"`
	ModifierName string    `json:"modifier_name"`
	ExtraPrice   string    `json:"extra_price"`
}

func (q *Queries) GetReceiptItemModifiers(ctx context.Context, dollar_1 []uuid.UUID) ([]GetReceiptItemModifiersRow, error) {
	rows, err := q.db.QueryContext(ctx, getReceiptItemModifiers, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReceiptItemModifiersRow{}
	for rows.Next() {
		var i GetReceiptItemModifiersRow
		if err := rows.Scan(&i.OrderItemID, &i.ModifierName, &i.ExtraPrice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReceiptItems = `-- name: GetReceiptItems :many
SELECT
    oi.id           AS item_id,
    mi.name         AS item_name,
    oi.quantity,
    oi.unit_price,
    oi.subtotal,
    oi.notes
FROM order_items oi
JOIN menu_items mi ON mi.id = oi.menu_item_id
WHERE oi.order_id = $1
ORDER BY oi.id
`

type GetReceiptItemsRow struct {
	ItemID    uuid.UUID `json:"item_id"`
	ItemName  string    `json:"item_name"`
	Quantity  int32     `json:"quantity"`
	UnitPrice string    `json:"unit_price"`
	Subtotal  string    `json:"subtotal"`
	Notes     string    `json:"notes"`
}

func (q *Queries) GetReceiptItems(ctx context.Context, orderID uuid.UUID) ([]GetReceiptItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getReceiptItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReceiptItemsRow{}
	for rows.Next() {
		var i GetReceiptItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemName,
			&i.Quantity,
			&i.UnitPrice,
			&i.Subtotal,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
