// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shift.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const closeShift = `-- name: CloseShift :one
UPDATE shifts
SET
    is_open          = false,
    ended_at         = NOW(),
    total_orders     = $2,
    total_revenue    = $3,
    cash_revenue     = $4,
    qris_revenue     = $5,
    transfer_revenue = $6,
    cancelled_orders = $7
WHERE id = $1
RETURNING id, business_id, branch_id, cashier_id, started_at, ended_at, is_open, total_orders, total_revenue, cash_revenue, qris_revenue, transfer_revenue, cancelled_orders, created_at
`

type CloseShiftParams struct {
	ID              uuid.UUID      `json:"id"`
	TotalOrders     sql.NullInt32  `json:"total_orders"`
	TotalRevenue    sql.NullString `json:"total_revenue"`
	CashRevenue     sql.NullString `json:"cash_revenue"`
	QrisRevenue     sql.NullString `json:"qris_revenue"`
	TransferRevenue sql.NullString `json:"transfer_revenue"`
	CancelledOrders sql.NullInt32  `json:"cancelled_orders"`
}

func (q *Queries) CloseShift(ctx context.Context, arg CloseShiftParams) (Shift, error) {
	row := q.db.QueryRowContext(ctx, closeShift,
		arg.ID,
		arg.TotalOrders,
		arg.TotalRevenue,
		arg.CashRevenue,
		arg.QrisRevenue,
		arg.TransferRevenue,
		arg.CancelledOrders,
	)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BranchID,
		&i.CashierID,
		&i.StartedAt,
		&i.EndedAt,
		&i.IsOpen,
		&i.TotalOrders,
		&i.TotalRevenue,
		&i.CashRevenue,
		&i.QrisRevenue,
		&i.TransferRevenue,
		&i.CancelledOrders,
		&i.CreatedAt,
	)
	return i, err
}

const getBranchShiftOrderStats = `-- name: GetBranchShiftOrderStats :one
SELECT
    COUNT(*) FILTER (WHERE o.status = 'paid')       AS total_orders,
    COUNT(*) FILTER (WHERE o.status = 'cancelled')  AS cancelled_orders,
    COALESCE(SUM(t.total) FILTER (WHERE o.status = 'paid'), 0) AS total_revenue,
    COALESCE(SUM(t.total) FILTER (
        WHERE o.status = 'paid' AND p.method = 'cash'
    ), 0) AS cash_revenue,
    COALESCE(SUM(t.total) FILTER (
        WHERE o.status = 'paid' AND p.method = 'qris'
    ), 0) AS qris_revenue,
    COALESCE(SUM(t.total) FILTER (
        WHERE o.status = 'paid' AND p.method = 'transfer'
    ), 0) AS transfer_revenue
FROM orders o
LEFT JOIN transactions t ON t.order_id = o.id
LEFT JOIN payments p ON p.order_id = o.id
WHERE o.branch_id   = $1
  AND o.business_id = $2
  AND o.created_at >= $3
  AND o.created_at <= $4
`

type GetBranchShiftOrderStatsParams struct {
	BranchID    uuid.UUID `json:"branch_id"`
	BusinessID  uuid.UUID `json:"business_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetBranchShiftOrderStatsRow struct {
	TotalOrders     int64       `json:"total_orders"`
	CancelledOrders int64       `json:"cancelled_orders"`
	TotalRevenue    interface{} `json:"total_revenue"`
	CashRevenue     interface{} `json:"cash_revenue"`
	QrisRevenue     interface{} `json:"qris_revenue"`
	TransferRevenue interface{} `json:"transfer_revenue"`
}

// Aggregate for all cashiers in a branch within a time range
func (q *Queries) GetBranchShiftOrderStats(ctx context.Context, arg GetBranchShiftOrderStatsParams) (GetBranchShiftOrderStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getBranchShiftOrderStats,
		arg.BranchID,
		arg.BusinessID,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	var i GetBranchShiftOrderStatsRow
	err := row.Scan(
		&i.TotalOrders,
		&i.CancelledOrders,
		&i.TotalRevenue,
		&i.CashRevenue,
		&i.QrisRevenue,
		&i.TransferRevenue,
	)
	return i, err
}

const getOpenShiftByCashier = `-- name: GetOpenShiftByCashier :one
SELECT id, business_id, branch_id, cashier_id, started_at, ended_at, is_open, total_orders, total_revenue, cash_revenue, qris_revenue, transfer_revenue, cancelled_orders, created_at FROM shifts
WHERE cashier_id = $1
  AND branch_id = $2
  AND is_open = true
LIMIT 1
`

type GetOpenShiftByCashierParams struct {
	CashierID uuid.UUID `json:"cashier_id"`
	BranchID  uuid.UUID `json:"branch_id"`
}

func (q *Queries) GetOpenShiftByCashier(ctx context.Context, arg GetOpenShiftByCashierParams) (Shift, error) {
	row := q.db.QueryRowContext(ctx, getOpenShiftByCashier, arg.CashierID, arg.BranchID)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BranchID,
		&i.CashierID,
		&i.StartedAt,
		&i.EndedAt,
		&i.IsOpen,
		&i.TotalOrders,
		&i.TotalRevenue,
		&i.CashRevenue,
		&i.QrisRevenue,
		&i.TransferRevenue,
		&i.CancelledOrders,
		&i.CreatedAt,
	)
	return i, err
}

const getShiftByID = `-- name: GetShiftByID :one
SELECT id, business_id, branch_id, cashier_id, started_at, ended_at, is_open, total_orders, total_revenue, cash_revenue, qris_revenue, transfer_revenue, cancelled_orders, created_at FROM shifts
WHERE id = $1 AND business_id = $2
LIMIT 1
`

type GetShiftByIDParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetShiftByID(ctx context.Context, arg GetShiftByIDParams) (Shift, error) {
	row := q.db.QueryRowContext(ctx, getShiftByID, arg.ID, arg.BusinessID)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BranchID,
		&i.CashierID,
		&i.StartedAt,
		&i.EndedAt,
		&i.IsOpen,
		&i.TotalOrders,
		&i.TotalRevenue,
		&i.CashRevenue,
		&i.QrisRevenue,
		&i.TransferRevenue,
		&i.CancelledOrders,
		&i.CreatedAt,
	)
	return i, err
}

const getShiftOrderStats = `-- name: GetShiftOrderStats :one
SELECT
    COUNT(*) FILTER (WHERE o.status = 'paid')       AS total_orders,
    COUNT(*) FILTER (WHERE o.status = 'cancelled')  AS cancelled_orders,
    COALESCE(SUM(t.total) FILTER (WHERE o.status = 'paid'), 0) AS total_revenue,
    COALESCE(SUM(t.total) FILTER (
        WHERE o.status = 'paid' AND p.method = 'cash'
    ), 0) AS cash_revenue,
    COALESCE(SUM(t.total) FILTER (
        WHERE o.status = 'paid' AND p.method = 'qris'
    ), 0) AS qris_revenue,
    COALESCE(SUM(t.total) FILTER (
        WHERE o.status = 'paid' AND p.method = 'transfer'
    ), 0) AS transfer_revenue
FROM orders o
LEFT JOIN transactions t ON t.order_id = o.id
LEFT JOIN payments p ON p.order_id = o.id
WHERE o.cashier_id = $1
  AND o.branch_id  = $2
  AND o.created_at >= $3
  AND o.created_at <= $4
`

type GetShiftOrderStatsParams struct {
	CashierID   uuid.UUID `json:"cashier_id"`
	BranchID    uuid.UUID `json:"branch_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetShiftOrderStatsRow struct {
	TotalOrders     int64       `json:"total_orders"`
	CancelledOrders int64       `json:"cancelled_orders"`
	TotalRevenue    interface{} `json:"total_revenue"`
	CashRevenue     interface{} `json:"cash_revenue"`
	QrisRevenue     interface{} `json:"qris_revenue"`
	TransferRevenue interface{} `json:"transfer_revenue"`
}

// Aggregate orders within shift time range for a cashier
func (q *Queries) GetShiftOrderStats(ctx context.Context, arg GetShiftOrderStatsParams) (GetShiftOrderStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getShiftOrderStats,
		arg.CashierID,
		arg.BranchID,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	var i GetShiftOrderStatsRow
	err := row.Scan(
		&i.TotalOrders,
		&i.CancelledOrders,
		&i.TotalRevenue,
		&i.CashRevenue,
		&i.QrisRevenue,
		&i.TransferRevenue,
	)
	return i, err
}

const getShiftTopItems = `-- name: GetShiftTopItems :many
SELECT
    mi.id           AS menu_item_id,
    mi.name         AS menu_item_name,
    mi.category,
    SUM(oi.quantity)    AS total_qty,
    SUM(oi.subtotal)    AS total_revenue
FROM order_items oi
JOIN menu_items mi ON mi.id = oi.menu_item_id
JOIN orders o      ON o.id  = oi.order_id
WHERE o.cashier_id = $1
  AND o.branch_id  = $2
  AND o.status     = 'paid'
  AND o.created_at >= $3
  AND o.created_at <= $4
GROUP BY mi.id, mi.name, mi.category
ORDER BY total_qty DESC
LIMIT 5
`

type GetShiftTopItemsParams struct {
	CashierID   uuid.UUID `json:"cashier_id"`
	BranchID    uuid.UUID `json:"branch_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetShiftTopItemsRow struct {
	MenuItemID   uuid.UUID `json:"menu_item_id"`
	MenuItemName string    `json:"menu_item_name"`
	Category     string    `json:"category"`
	TotalQty     int64     `json:"total_qty"`
	TotalRevenue int64     `json:"total_revenue"`
}

// Top 5 selling items within shift time range
func (q *Queries) GetShiftTopItems(ctx context.Context, arg GetShiftTopItemsParams) ([]GetShiftTopItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getShiftTopItems,
		arg.CashierID,
		arg.BranchID,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetShiftTopItemsRow{}
	for rows.Next() {
		var i GetShiftTopItemsRow
		if err := rows.Scan(
			&i.MenuItemID,
			&i.MenuItemName,
			&i.Category,
			&i.TotalQty,
			&i.TotalRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftsByBranch = `-- name: ListShiftsByBranch :many
SELECT s.id, s.business_id, s.branch_id, s.cashier_id, s.started_at, s.ended_at, s.is_open, s.total_orders, s.total_revenue, s.cash_revenue, s.qris_revenue, s.transfer_revenue, s.cancelled_orders, s.created_at, u.name as cashier_name
FROM shifts s
JOIN users u ON u.id = s.cashier_id
WHERE s.branch_id = $1
  AND s.business_id = $2
ORDER BY s.started_at DESC
LIMIT 100
`

type ListShiftsByBranchParams struct {
	BranchID   uuid.UUID `json:"branch_id"`
	BusinessID uuid.UUID `json:"business_id"`
}

type ListShiftsByBranchRow struct {
	ID              uuid.UUID      `json:"id"`
	BusinessID      uuid.UUID      `json:"business_id"`
	BranchID        uuid.UUID      `json:"branch_id"`
	CashierID       uuid.UUID      `json:"cashier_id"`
	StartedAt       time.Time      `json:"started_at"`
	EndedAt         sql.NullTime   `json:"ended_at"`
	IsOpen          bool           `json:"is_open"`
	TotalOrders     sql.NullInt32  `json:"total_orders"`
	TotalRevenue    sql.NullString `json:"total_revenue"`
	CashRevenue     sql.NullString `json:"cash_revenue"`
	QrisRevenue     sql.NullString `json:"qris_revenue"`
	TransferRevenue sql.NullString `json:"transfer_revenue"`
	CancelledOrders sql.NullInt32  `json:"cancelled_orders"`
	CreatedAt       time.Time      `json:"created_at"`
	CashierName     string         `json:"cashier_name"`
}

func (q *Queries) ListShiftsByBranch(ctx context.Context, arg ListShiftsByBranchParams) ([]ListShiftsByBranchRow, error) {
	rows, err := q.db.QueryContext(ctx, listShiftsByBranch, arg.BranchID, arg.BusinessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShiftsByBranchRow{}
	for rows.Next() {
		var i ListShiftsByBranchRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.BranchID,
			&i.CashierID,
			&i.StartedAt,
			&i.EndedAt,
			&i.IsOpen,
			&i.TotalOrders,
			&i.TotalRevenue,
			&i.CashRevenue,
			&i.QrisRevenue,
			&i.TransferRevenue,
			&i.CancelledOrders,
			&i.CreatedAt,
			&i.CashierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftsByCashier = `-- name: ListShiftsByCashier :many
SELECT id, business_id, branch_id, cashier_id, started_at, ended_at, is_open, total_orders, total_revenue, cash_revenue, qris_revenue, transfer_revenue, cancelled_orders, created_at FROM shifts
WHERE cashier_id = $1
  AND business_id = $2
ORDER BY started_at DESC
LIMIT 50
`

type ListShiftsByCashierParams struct {
	CashierID  uuid.UUID `json:"cashier_id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) ListShiftsByCashier(ctx context.Context, arg ListShiftsByCashierParams) ([]Shift, error) {
	rows, err := q.db.QueryContext(ctx, listShiftsByCashier, arg.CashierID, arg.BusinessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shift{}
	for rows.Next() {
		var i Shift
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.BranchID,
			&i.CashierID,
			&i.StartedAt,
			&i.EndedAt,
			&i.IsOpen,
			&i.TotalOrders,
			&i.TotalRevenue,
			&i.CashRevenue,
			&i.QrisRevenue,
			&i.TransferRevenue,
			&i.CancelledOrders,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openShift = `-- name: OpenShift :one
INSERT INTO shifts (id, business_id, branch_id, cashier_id, started_at, is_open, created_at)
VALUES ($1, $2, $3, $4, NOW(), true, NOW())
RETURNING id, business_id, branch_id, cashier_id, started_at, ended_at, is_open, total_orders, total_revenue, cash_revenue, qris_revenue, transfer_revenue, cancelled_orders, created_at
`

type OpenShiftParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
	BranchID   uuid.UUID `json:"branch_id"`
	CashierID  uuid.UUID `json:"cashier_id"`
}

func (q *Queries) OpenShift(ctx context.Context, arg OpenShiftParams) (Shift, error) {
	row := q.db.QueryRowContext(ctx, openShift,
		arg.ID,
		arg.BusinessID,
		arg.BranchID,
		arg.CashierID,
	)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BranchID,
		&i.CashierID,
		&i.StartedAt,
		&i.EndedAt,
		&i.IsOpen,
		&i.TotalOrders,
		&i.TotalRevenue,
		&i.CashRevenue,
		&i.QrisRevenue,
		&i.TransferRevenue,
		&i.CancelledOrders,
		&i.CreatedAt,
	)
	return i, err
}
