// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createStaff = `-- name: CreateStaff :one
INSERT INTO users (business_id, branch_id, name, email, password_hash, role)
VALUES ($1, $2, $3, $4, $5, 'cashier')
RETURNING id, business_id, branch_id, name, email, password_hash, role, is_active, created_at
`

type CreateStaffParams struct {
	BusinessID   uuid.UUID     `json:"business_id"`
	BranchID     uuid.NullUUID `json:"branch_id"`
	Name         string        `json:"name"`
	Email        string        `json:"email"`
	PasswordHash string        `json:"password_hash"`
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createStaff,
		arg.BusinessID,
		arg.BranchID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BranchID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getStaffByID = `-- name: GetStaffByID :one
SELECT id, business_id, branch_id, name, email, password_hash, role, is_active, created_at
FROM users
WHERE id          = $1
  AND business_id = $2
LIMIT 1
`

type GetStaffByIDParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetStaffByID(ctx context.Context, arg GetStaffByIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getStaffByID, arg.ID, arg.BusinessID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BranchID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listStaff = `-- name: ListStaff :many
SELECT id, business_id, branch_id, name, email, password_hash, role, is_active, created_at
FROM users
WHERE business_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListStaff(ctx context.Context, businessID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listStaff, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.BranchID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStaffStatus = `-- name: UpdateStaffStatus :one
UPDATE users
SET is_active = $2
WHERE id          = $1
  AND business_id = $3
  AND role        != 'owner'
RETURNING id, business_id, branch_id, name, email, password_hash, role, is_active, created_at
`

type UpdateStaffStatusParams struct {
	ID         uuid.UUID `json:"id"`
	IsActive   bool      `json:"is_active"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) UpdateStaffStatus(ctx context.Context, arg UpdateStaffStatusParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateStaffStatus, arg.ID, arg.IsActive, arg.BusinessID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BranchID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
