// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: table.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTable = `-- name: CreateTable :one
INSERT INTO tables (branch_id, name, qr_code)
VALUES ($1, $2, $3)
RETURNING id, branch_id, name, qr_code, status, created_at, reserved_by, reserved_note, updated_at
`

type CreateTableParams struct {
	BranchID uuid.UUID `json:"branch_id"`
	Name     string    `json:"name"`
	QrCode   string    `json:"qr_code"`
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (Table, error) {
	row := q.db.QueryRowContext(ctx, createTable, arg.BranchID, arg.Name, arg.QrCode)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.QrCode,
		&i.Status,
		&i.CreatedAt,
		&i.ReservedBy,
		&i.ReservedNote,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveOrderByTable = `-- name: GetActiveOrderByTable :one
SELECT id FROM orders
WHERE table_id = $1
  AND status = 'open'
LIMIT 1
`

func (q *Queries) GetActiveOrderByTable(ctx context.Context, tableID uuid.NullUUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getActiveOrderByTable, tableID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getTableByID = `-- name: GetTableByID :one
SELECT t.id, t.branch_id, t.name, t.qr_code, t.status, t.created_at, t.reserved_by, t.reserved_note, t.updated_at
FROM tables t
JOIN branches b ON b.id = t.branch_id
WHERE t.id          = $1
  AND b.business_id = $2
LIMIT 1
`

type GetTableByIDParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetTableByID(ctx context.Context, arg GetTableByIDParams) (Table, error) {
	row := q.db.QueryRowContext(ctx, getTableByID, arg.ID, arg.BusinessID)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.QrCode,
		&i.Status,
		&i.CreatedAt,
		&i.ReservedBy,
		&i.ReservedNote,
		&i.UpdatedAt,
	)
	return i, err
}

const getTableByIDForUpdate = `-- name: GetTableByIDForUpdate :one
SELECT id, branch_id, name, qr_code, status, created_at, reserved_by, reserved_note, updated_at FROM tables
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetTableByIDForUpdate(ctx context.Context, id uuid.UUID) (Table, error) {
	row := q.db.QueryRowContext(ctx, getTableByIDForUpdate, id)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.QrCode,
		&i.Status,
		&i.CreatedAt,
		&i.ReservedBy,
		&i.ReservedNote,
		&i.UpdatedAt,
	)
	return i, err
}

const listTables = `-- name: ListTables :many
SELECT t.id, t.branch_id, t.name, t.qr_code, t.status, t.created_at, t.reserved_by, t.reserved_note, t.updated_at
FROM tables t
JOIN branches b ON b.id = t.branch_id
WHERE b.business_id = $1
  AND t.branch_id   = $2
ORDER BY t.name ASC
`

type ListTablesParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	BranchID   uuid.UUID `json:"branch_id"`
}

func (q *Queries) ListTables(ctx context.Context, arg ListTablesParams) ([]Table, error) {
	rows, err := q.db.QueryContext(ctx, listTables, arg.BusinessID, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Name,
			&i.QrCode,
			&i.Status,
			&i.CreatedAt,
			&i.ReservedBy,
			&i.ReservedNote,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTablesByBranch = `-- name: ListTablesByBranch :many
SELECT id, branch_id, name, qr_code, status, created_at, reserved_by, reserved_note, updated_at FROM tables
WHERE branch_id = $1
ORDER BY name ASC
`

func (q *Queries) ListTablesByBranch(ctx context.Context, branchID uuid.UUID) ([]Table, error) {
	rows, err := q.db.QueryContext(ctx, listTablesByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Name,
			&i.QrCode,
			&i.Status,
			&i.CreatedAt,
			&i.ReservedBy,
			&i.ReservedNote,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTablesByBusiness = `-- name: ListTablesByBusiness :many
SELECT t.id, t.branch_id, t.name, t.qr_code, t.status, t.created_at, t.reserved_by, t.reserved_note, t.updated_at
FROM tables t
JOIN branches b ON b.id = t.branch_id
WHERE b.business_id = $1
ORDER BY t.name ASC
`

func (q *Queries) ListTablesByBusiness(ctx context.Context, businessID uuid.UUID) ([]Table, error) {
	rows, err := q.db.QueryContext(ctx, listTablesByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Name,
			&i.QrCode,
			&i.Status,
			&i.CreatedAt,
			&i.ReservedBy,
			&i.ReservedNote,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTableAvailable = `-- name: SetTableAvailable :one
UPDATE tables
SET status = 'available', reserved_by = NULL, reserved_note = NULL, updated_at = NOW()
WHERE id = $1
RETURNING id, branch_id, name, qr_code, status, created_at, reserved_by, reserved_note, updated_at
`

func (q *Queries) SetTableAvailable(ctx context.Context, id uuid.UUID) (Table, error) {
	row := q.db.QueryRowContext(ctx, setTableAvailable, id)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.QrCode,
		&i.Status,
		&i.CreatedAt,
		&i.ReservedBy,
		&i.ReservedNote,
		&i.UpdatedAt,
	)
	return i, err
}

const setTableOccupied = `-- name: SetTableOccupied :one
UPDATE tables
SET status = 'occupied', reserved_by = NULL, reserved_note = NULL, updated_at = NOW()
WHERE id = $1
RETURNING id, branch_id, name, qr_code, status, created_at, reserved_by, reserved_note, updated_at
`

func (q *Queries) SetTableOccupied(ctx context.Context, id uuid.UUID) (Table, error) {
	row := q.db.QueryRowContext(ctx, setTableOccupied, id)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.QrCode,
		&i.Status,
		&i.CreatedAt,
		&i.ReservedBy,
		&i.ReservedNote,
		&i.UpdatedAt,
	)
	return i, err
}

const setTableReserved = `-- name: SetTableReserved :one
UPDATE tables
SET status = 'reserved', reserved_by = $2, reserved_note = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, branch_id, name, qr_code, status, created_at, reserved_by, reserved_note, updated_at
`

type SetTableReservedParams struct {
	ID           uuid.UUID      `json:"id"`
	ReservedBy   uuid.NullUUID  `json:"reserved_by"`
	ReservedNote sql.NullString `json:"reserved_note"`
}

func (q *Queries) SetTableReserved(ctx context.Context, arg SetTableReservedParams) (Table, error) {
	row := q.db.QueryRowContext(ctx, setTableReserved, arg.ID, arg.ReservedBy, arg.ReservedNote)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.QrCode,
		&i.Status,
		&i.CreatedAt,
		&i.ReservedBy,
		&i.ReservedNote,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTable = `-- name: UpdateTable :one
UPDATE tables
SET
    name    = COALESCE($2, name),
    qr_code = COALESCE($3, qr_code),
    status  = COALESCE($4, status)
WHERE id = $1
RETURNING id, branch_id, name, qr_code, status, created_at, reserved_by, reserved_note, updated_at
`

type UpdateTableParams struct {
	ID     uuid.UUID   `json:"id"`
	Name   string      `json:"name"`
	QrCode string      `json:"qr_code"`
	Status TableStatus `json:"status"`
}

func (q *Queries) UpdateTable(ctx context.Context, arg UpdateTableParams) (Table, error) {
	row := q.db.QueryRowContext(ctx, updateTable,
		arg.ID,
		arg.Name,
		arg.QrCode,
		arg.Status,
	)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.QrCode,
		&i.Status,
		&i.CreatedAt,
		&i.ReservedBy,
		&i.ReservedNote,
		&i.UpdatedAt,
	)
	return i, err
}
